services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "uv run pytest"
    working_dir: /usr/workspace
    environment:
      - LOGIN=${LOGIN}
